name: ci cd demo

on:
  push:
    branches:
      - 'feature/chalice'
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: chalice deploy
      uses: 5tigerjelly/chalice-action@master
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: AKIAS6RSXNGBVC5YMSVP
        AWS_SECRET_ACCESS_KEY: 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
        AWS_DEFAULT_REGION: us-east-1